### PR TITLE
Docs syntax improvements

### PR DESCRIPTION
**Pull request by jonashaag**
(Untested)

### CODE REVIEW

**Comment by kklein** [comment]
Do you want me to point read the docs to this branch?

**Comment by jonashaag** [comment]
Does RTD support branch builds? Or I guess we should make a docs build part of the CI (with no dependency on RTD)

**Comment by kklein** [comment]
I tried to enable building documentation for PRs. There is also some functionality to integrate that as part of CI but I'm afraid I don't have sufficient permissions to do so.

https://datajudge.readthedocs.io/en/jonashaag-patch-1/

**Comment by jonashaag** [comment]
Nice, the links seems to work so this is ready to review

**Review by kklein — APPROVED** [review]
Thanks!

**Comment by kklein** [comment]
Hi @jonashaag ! Should we merge this?

**Pull request merged**
